apiVersion: v1
kind: Service
metadata:
  name: imagescaler
  labels:
    app: imagescaler
spec:
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
  selector:
    app: imagescaler
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagescaler
  labels:
    app: imagescaler
spec:
  selector:
    matchLabels:
      app: imagescaler
  template:
    metadata:
      labels:
        app: imagescaler
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5001"
        prometheus.io/path: "/metrics"
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccount: imagescaler
      containers:
        - name: imagescaler
          image: # Image needs building
          command: []
          args: []
          ports:
            - containerPort: 50051
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 768Mi
              cpu: 2500m
          readinessProbe:
            exec:
              command:
                ["/bin/grpc_health_probe", "-addr=:50051"]
          livenessProbe:
            exec:
              command:
                ["/bin/grpc_health_probe", "-addr=:50051"]
