name: Terraform plan & apply

on:
  push:
    paths:
      - sre/iac/**

jobs:
  terraform:
    runs-on: ubuntu-24.04
    name: Terraform
    defaults:
      run:
        shell: bash
        working-directory: sre/iac/

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.2"

      - name: Terraform init
        run: terraform init
        env: 
          GOOGLE_CREDENTIALS: ${{secrets.GKE_SA_KEY}}

      - name: Terraform plan
        run: terraform plan -input=false -var-file=./cicd.tfvars
        env: 
          GOOGLE_CREDENTIALS: ${{secrets.GKE_SA_KEY}}

      - name: Terraform apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -input=false -var-file=./cicd.tfvars
        env: 
          GOOGLE_CREDENTIALS: ${{secrets.GKE_SA_KEY}}
